# Generated by Django 5.0.4 on 2024-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
