# Generated by Django 5.0.4 on 2024-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_post_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
    ]
